2016-10-01 15:10:21,430 manager INFO 1.1.0
2016-10-01 15:10:21,430 manager INFO Copyright (C) 2003-2010
2016-10-01 15:10:21,430 manager INFO   Noriaki Ando
2016-10-01 15:10:21,430 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-01 15:10:21,430 manager INFO Manager starting.
2016-10-01 15:10:21,430 manager INFO Starting local logging.
2016-10-01 15:10:21,438 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-01 15:10:23,463 ManagerServant INFO Master manager not found
2016-10-01 15:10:23,467 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-01 15:10:23,467 LocalServiceAdmin INFO All the local services are enabled.
2016-10-01 15:10:23,486 ec_base INFO setRate(1000000.000000) done
2016-10-01 15:10:23,487 ec_base INFO setRate(1000.000000) done
2016-10-01 15:10:23,489 rtobject INFO 1 execution context was created.
2016-10-01 15:10:23,500 rtobject INFO Initial active configuration set is default.
2016-10-01 15:10:27,447 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-01 15:10:27,448 SdoServiceAdmin ERROR type  already exists.
2016-10-01 15:10:27,453 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-01 15:10:27,453 SdoServiceAdmin ERROR type de9d2e1e-7287-4987-aa3c-14c419b5b53c already exists.
2016-10-01 15:10:58,364 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1319, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 278, in onActivated
    self.SPort=serial.Serial(self._Port[0],timeout=TimeOut)
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\serial\serialutil.py", line 182, in __init__
    self.open()
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM12': WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')

2016-10-01 15:10:58,368 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 333, in onExecute
    self.Send(0x02,VL*CntPM)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-10-01 15:10:58,368 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1359, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 304, in onDeactivated
    self.Send(0x78,False)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-10-01 15:11:22,154 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1319, in on_activated
    ret = self.onActivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 278, in onActivated
    self.SPort=serial.Serial(self._Port[0],timeout=TimeOut)
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\serial\serialutil.py", line 182, in __init__
    self.open()
  File "C:\Python27\Lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
SerialException: could not open port 'COM12': WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')

2016-10-01 15:11:22,155 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 333, in onExecute
    self.Send(0x02,VL*CntPM)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-10-01 15:11:22,157 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\RTObject.py", line 1359, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 304, in onDeactivated
    self.Send(0x78,False)
  File "C:\Users\robot\Desktop\Zumo\Zumo.py", line 370, in Send
    self.SPort.write(MakeData(ID,Data))
AttributeError: 'NoneType' object has no attribute 'write'

2016-10-01 15:11:35,904 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 15:11:50,332 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:11:55,390 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:11:58,961 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 15:12:03,657 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 15:12:03,657 ec_worker WARNING ExecutionContext is already stopped.
2016-10-01 15:12:03,657 ec_base ERROR Invoking on_shutdown() for each RTC failed.
2016-10-01 15:12:03,664 ec_worker WARNING ExecutionContext is already stopped.
2016-10-01 15:12:03,664 ec_base ERROR Invoking on_shutdown() for each RTC failed.
