2016-10-01 15:01:56,036 manager INFO 1.1.0
2016-10-01 15:01:56,038 manager INFO Copyright (C) 2003-2010
2016-10-01 15:01:56,038 manager INFO   Noriaki Ando
2016-10-01 15:01:56,038 manager INFO   Intelligent Systems Research Institute, AIST
2016-10-01 15:01:56,038 manager INFO Manager starting.
2016-10-01 15:01:56,038 manager INFO Starting local logging.
2016-10-01 15:01:56,046 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2016-10-01 15:01:58,065 ManagerServant INFO Master manager not found
2016-10-01 15:01:58,069 manager WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2016-10-01 15:01:58,071 LocalServiceAdmin INFO All the local services are enabled.
2016-10-01 15:01:58,091 ec_base INFO setRate(1000000.000000) done
2016-10-01 15:01:58,092 ec_base INFO setRate(1000.000000) done
2016-10-01 15:01:58,094 rtobject INFO 1 execution context was created.
2016-10-01 15:01:58,105 rtobject INFO Initial active configuration set is default.
2016-10-01 15:02:25,757 SdoServiceAdmin WARNING No available SDO service in the factory: 
2016-10-01 15:02:25,757 SdoServiceAdmin ERROR type  already exists.
2016-10-01 15:02:25,765 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2016-10-01 15:02:25,765 SdoServiceAdmin ERROR type 5e459304-86a0-4090-82c3-15b2cb648090 already exists.
2016-10-01 15:04:59,654 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:10:05,444 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2016-10-01 15:13:41,267 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:14:05,571 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:15:37,832 ec_worker ERROR State of the RTC is not INACTIVE_STATE.
2016-10-01 15:15:53,512 InPortCorbaCdrConsumer ERROR Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\InPortCorbaCdrConsumer.py", line 157, in put
    return self.convertReturnCode(inportcdr.put(data))
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\DataPort_idl.py", line 79, in put
    return self._obj.invoke("put", _0_OpenRTM.InPortCdr._d_put, args)
COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_WaitingForReply, CORBA.COMPLETED_MAYBE)

2016-10-01 15:15:54,507 Velocity WARNING Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\OpenRTM_aist\PortBase.py", line 1624, in disconnectNext
    return p.notify_disconnect(connector_profile.connector_id)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\RTC_idl.py", line 1207, in notify_disconnect
    return self._obj.invoke("notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

